name: smtlog

services:
  backend:
    build: ./apps/backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file: .env
    environment:
      PORT: ${BACKEND_PORT}
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost/health']
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ./database.sqlite:/app/database.sqlite
    networks:
      - smtlog-net

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - '${FRONTEND_PORT}:80'
    env_file: .env
    environment:
      API_URL: http://${BACKEND_HOST}:${BACKEND_PORT}/
    depends_on:
      - backend
    networks:
      - smtlog-net

networks:
  smtlog-net:
